/* Generated by edgenlu export. Do not edit. */
#ifndef ENLU_MODEL_DATA_H
#define ENLU_MODEL_DATA_H

#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

extern const unsigned char enlu_model_data[];
extern const size_t enlu_model_data_len;

#ifdef __cplusplus
}
#endif

#endif /* ENLU_MODEL_DATA_H */
