/* Generated by tinycue export. Do not edit. */
#ifndef TCUE_MODEL_DATA_H
#define TCUE_MODEL_DATA_H

#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

extern const unsigned char tcue_model_data[];
extern const size_t tcue_model_data_len;

#ifdef __cplusplus
}
#endif

#endif /* TCUE_MODEL_DATA_H */
